import {readFileSync,writeFileSync} from 'node:fs';
const content=JSON.parse(readFileSync(new URL('./content.json',import.meta.url),'utf8'));
const {pages,assets}=content;
const BASE='/utkarsh-portfolio/';
const SITE='https://utkmohan.github.io'+BASE;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const text=s=>s.replace(/<[^>]*>/g,'').replaceAll('&amp;','&').trim();
const inner=s=>s.replace(/^<(p|h[1-6]|li)>|<\/(p|h[1-6]|li)>$/g,'');
const sec=(p,i)=>pages[p].sections[i];
const html=(p,i)=>sec(p,i).blocks.join('\n');
const route=p=>BASE+(p==='home'?'':p+'.html');
const resume='https://drive.google.com/file/d/1doZb4_H2f8BxI5vQDJPdiE1VG_G83sib/view';
const study='https://drive.google.com/file/d/1KgmbUFxuwheX29idRQ7CfwBsv5vd66nu/view?usp=sharing';
const paper='https://dl.acm.org/doi/pdf/10.1145/3716368.3735230';
const paperTitle='An Efficient Distributed Machine Learning Inference Framework with Byzantine Fault Detection';
const socials=[['ORCID','https://orcid.org/0009-0007-1210-5538'],['LinkedIn','http://www.linkedin.com/in/umohan2000'],['Resume',resume],['YouTube','http://www.youtube.com/@thatlostboyandhissoul'],['Instagram','https://www.instagram.com/schwitz.jpeg/']];
const byId=Object.fromEntries(assets.map(a=>[a.id,a]));
function img(id,{eager=false,large=false}={}){const a=byId[id];if(!a)throw Error('Missing asset '+id);return `<img src="${BASE}assets/${id}-${large?'large':'thumb'}.webp" width="${a.width}" height="${a.height}" alt="${esc(a.alt)}" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}>`;}
function photo(id,group,caption=''){const a=byId[id];const cap=caption||a.caption;return `<figure><a class="photo-link" href="${BASE}assets/${id}-large.webp" data-gallery="${esc(group)}" data-caption="${esc(cap)}" aria-label="Enlarge: ${esc(a.alt)}">${img(id)}<span class="enlarge" aria-hidden="true">↗</span></a>${cap?`<figcaption>${esc(cap)}</figcaption>`:''}</figure>`;}
const eyebrow=(n,s)=>`<p class="eyebrow"><span>${n}</span> ${s}</p>`;
const heading=(n,title,extra='')=>`<div class="section-heading">${eyebrow(n,extra)}<h2>${title}</h2></div>`;
const focus=sec('home',1).blocks[4];
function masthead(page,title,lead='',n=''){return `<header class="page-heading">${eyebrow(n||'FIELD NOTES',page)}<h1>${title}</h1>${lead?`<div class="intro">${lead}</div>`:''}</header>`;}
function layout(page,title,body,{image='image-002',description='Utkarsh Mohan is a PhD student at UC Merced working with Prof. Hyeran Jeon in the MoCA Lab, researching emerging memory and storage for LLM serving.'}={}){
 const selected=['conference-recap-glsvlsi-2025','graduation-usc-2025'].includes(page)?'blog':page;
 const nav=['home','research','teaching','photography','blog'].map(p=>`<a href="${route(p)}" ${selected===p?'aria-current="page"':''}>${p[0].toUpperCase()+p.slice(1)}</a>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>${esc(title)} — Utkarsh Mohan</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${route(page)==BASE?SITE:SITE+page+'.html'}"><meta property="og:title" content="${esc(title)} — Utkarsh Mohan"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="${selected==='blog'&&page!=='blog'?'article':'website'}"><meta property="og:url" content="${page==='home'?SITE:SITE+page+'.html'}"><meta property="og:image" content="${SITE}assets/${image}-large.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${BASE}favicon.svg" type="image/svg+xml"><script src="${BASE}theme.js"></script><link rel="stylesheet" href="${BASE}style.css"><script src="${BASE}app.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="monogram" href="${BASE}" aria-label="Utkarsh Mohan — Home">um<span>.</span></a><nav class="desktop-nav" aria-label="Main navigation">${nav}</nav><div class="nav-actions"><a class="contact-link" href="mailto:umohan@ucmerced.edu">Contact <span aria-hidden="true">↗</span></a><button id="theme-toggle" class="theme-toggle" aria-label="Switch to dark theme" hidden><span aria-hidden="true">◐</span></button><details class="mobile-menu"><summary>Menu <span aria-hidden="true">＋</span></summary><nav aria-label="Mobile navigation">${nav}<a href="${resume}">Resume ↗</a></nav></details></div></div></header><main id="main" tabindex="-1">${body}</main><footer class="site-footer"><div><a class="footer-name" href="${BASE}">Utkarsh Mohan<span> ↗</span></a><p>Research, photographs &amp; stories.</p></div><div class="footer-links">${socials.map(([n,u])=>`<a href="${esc(u)}">${n} ↗</a>`).join('')}<a href="mailto:umohan@ucmerced.edu">Email ↗</a></div><p class="copyright">© 2025 Utkarsh Mohan</p></footer><dialog id="lightbox" aria-labelledby="lightbox-title"><div class="lightbox-bar"><h2 id="lightbox-title">Photograph</h2><button id="lightbox-close" aria-label="Close photograph">Close ×</button></div><figure><img id="lightbox-image" alt=""><figcaption id="lightbox-caption" aria-live="polite"></figcaption></figure><div class="lightbox-controls"><button id="lightbox-prev" aria-label="Previous photograph">← Previous</button><span id="lightbox-count" aria-live="polite"></span><button id="lightbox-next" aria-label="Next photograph">Next →</button></div></dialog></body></html>`;
}
function newsItem(s){return s.replace(/\[([^\]]+)\]/,`<span class="news-date">[$1]</span>`);}
function home(){
 const b=sec('home',1).blocks;const news=sec('home',4).blocks;
 const groups={};news.slice(5).forEach(item=>{const y='20'+(text(item).match(/\[.*?'(\d{2})/)?.[1]||'25');(groups[y]??=[]).push(item);});
 const bio=b[2];
 return `<section class="hero"><div class="hero-copy">${eyebrow('01','RESEARCHER · EDUCATOR · PHOTOGRAPHER')}<h1>Utkarsh<br><em>Mohan</em><span class="name-dot" aria-hidden="true">.</span></h1><p class="hero-subtitle">Exploring the Future of Computing</p><div class="hero-affiliation">${bio}</div><div class="hero-focus">${focus}</div><div class="hero-links"><a class="button primary" href="${route('research')}">Explore research <span aria-hidden="true">↗</span></a><a class="button" href="${resume}">Resume ↗</a><a class="text-link" href="mailto:umohan@ucmerced.edu">Contact ↗</a></div></div><div class="portrait-column"><div class="portrait-frame"><span class="portrait-mark" aria-hidden="true">[ UM / 01 ]</span>${img(sec('home',1).images[0],{eager:true,large:true})}<span class="portrait-label">UC MERCED / MoCA LAB</span></div><div class="education">${b.slice(5).join('')}</div></div></section>
 <section class="about section-grid">${heading('02','A little<br>about me','BACKGROUND')}<div class="prose">${b[1]}${b[3]}<div class="social-row">${socials.map(([n,u])=>`<a href="${u}">${n} ↗</a>`).join('')}</div></div></section>
 <section class="section-grid news-section" id="news">${heading('03','On the<br>noticeboard','NEWS')}<div><ol class="news-list">${news.slice(0,5).map(newsItem).join('')}</ol><details class="news-archive"><summary><span>View all updates</span><span aria-hidden="true">＋</span></summary>${Object.keys(groups).sort().reverse().map(y=>`<h3 class="archive-year">${y}</h3><ol class="news-list">${groups[y].map(newsItem).join('')}</ol>`).join('')}</details></div></section>
 <section class="service-section">${heading('04','Service &amp; professional activities','COMMUNITY')}<div class="service-columns"><div><h3>Services</h3><ul>${sec('home',6).blocks.slice(0,3).join('')}</ul></div><div><h3>Professional activities</h3><ul>${sec('home',6).blocks.slice(3).join('')}</ul></div></div></section>
 <section class="collection-section">${heading('05','Recent conferences','BEYOND THE LAB')}<div class="photo-grid conference-grid">${sec('home',8).carousels.flat().map(id=>photo(id,'Recent conferences')).join('')}</div></section>
 <section class="collection-section">${heading('06','Intern experience','SK HYNIX AMERICA')}<div class="photo-grid conference-grid">${sec('home',10).carousels.flat().map(id=>photo(id,'Intern experience')).join('')}</div></section>
 <section class="awards-section">${heading('07','Recent awards','RECOGNITION')}<div class="awards-grid">${sec('home',12).images.map((id,i)=>`<article>${photo(id,'Recent awards',text(sec('home',12).blocks[i*2]))}${sec('home',12).blocks[i*2+1]}</article>`).join('')}</div></section>
 <section class="section-grid videos-section">${heading('08','Fun videos','OFF THE CLOCK')}<div class="video-list">${sec('home',14).videos.map((v,i)=>`<a href="${esc("https://www.youtube.com/watch?v="+new URL(v.url).pathname.split("/").pop())}"><span class="video-number">0${i+1}</span><span>${esc(v.title.replace(/^YouTube Video, /,''))}</span><span aria-hidden="true">▶</span></a>`).join('')}</div></section>
 <section class="contact-section"><p class="eyebrow">LET’S CONNECT</p>${sec('home',15).blocks.join('')}<a href="mailto:umohan@ucmerced.edu">umohan@ucmerced.edu <span aria-hidden="true">↗</span></a></section>`;
}
function research(){return `${masthead('Research','Research, Conferences <br>&amp; Presentations','', '02')}<section class="focus-banner">${eyebrow('NOW','RESEARCH FOCUS')}${focus}<span class="stack-lines" aria-hidden="true"><i></i><i></i><i></i><i></i></span></section><div class="research-list">${[1,2,3].map((n)=>{const s=sec('research',n);return `<article class="research-entry"><div class="research-meta">${eyebrow('0'+n,['','PUBLICATION · GLSVLSI 2025','RESEARCH EXPERIENCE','PRESENTATION'][n])}</div><div class="research-copy">${n===1?`<h2>${paperTitle}</h2><h3 class="original-title">${inner(s.blocks[0])}</h3>`:`<h2>${inner(s.blocks[0])}</h2>`}<div class="prose">${s.blocks.slice(1).join('')}</div>${n===1?`<a class="button primary" href="${paper}">Read the paper ↗</a><a class="text-link" href="https://www.glsvlsi.org/program.html#ts1c">Conference program ↗</a>`:''}</div><div class="research-image">${photo(s.images[0],'Research')}</div></article>`}).join('')}</div>`;}
function teaching(){
 let groups=[];for(const b of sec('teaching',2).blocks){if(b.startsWith('<p>'))groups.push({title:inner(b),roles:[]});else groups.at(-1).roles.push(b);}
 return `${masthead('Teaching','Teaching Experience',html('teaching',1),'03')}<aside class="study-guide"><div>${eyebrow('RESOURCE','CSE-015')}<h2>Discrete Mathematics study guide</h2></div><a class="button primary" href="${study}">Open study guide ↗</a></aside>${groups.map((g,i)=>`<section class="teaching-group section-grid">${heading('0'+(i+1),g.title,['UC MERCED','USC','K–12 / OUTREACH'][i])}<ol class="teaching-roles">${g.roles.map(b=>{let out=b.replace(/<br\s*\/>/,'</span><br><span class="semester">');out=out.replace('<li><p>','<li><p class="role-heading"><span>');out=out.replace('</p>','</span></p>');return out;}).join('')}</ol></section>`).join('')}`;
}
const albumNames=['Venice Beach, Los Angeles CA','Seattle, WA','Los Angeles Book Fair, USC','Miami, FL','Point Dume, Malibu CA','Sparks, USC, Los Angeles CA','USC Sports, CA','Graduation USC, CA'];
const albumShort=['Venice Beach','Seattle','LA Book Fair','Miami','Point Dume','Sparks at USC','USC Sports','USC Graduation'];
const albums=pages.photography.sections.flatMap(s=>s.carousels).map((ids,i)=>({ids,name:albumNames[i],short:albumShort[i],slug:'album-'+(i+1)}));
function photography(){return `<header class="photo-heading">${masthead('Photography','Moments Through <br><em>my Lens</em>',sec('photography',0).blocks.slice(1).join(''),'04')}<figure class="photo-intro-image">${img(sec('photography',0).images[0],{eager:true})}</figure></header><nav class="album-nav" aria-label="Photography albums"><a href="#all-albums" data-album="all" aria-current="true">All photographs <span>52</span></a>${albums.map(a=>`<a href="#${a.slug}" data-album="${a.slug}">${a.short} <span>${a.ids.length}</span></a>`).join('')}</nav><div id="all-albums">${albums.map((a,i)=>`<section class="album" id="${a.slug}" data-album-section><div class="album-title">${eyebrow('0'+(i+1),'COLLECTION')}<h2>${a.name}</h2><p>${a.ids.length} photographs</p></div><div class="photo-grid editorial-gallery">${a.ids.map((id,n)=>photo(id,a.name,byId[id].caption||`${a.name} · ${String(n+1).padStart(2,'0')}`)).join('')}</div></section>`).join('')}</div>`;}
const posts=content.posts;
function blog(){return `${masthead('Blog','Personal Thoughts',html('blog',1),'05')}<div class="post-list">${posts.map((post,i)=>{const b=sec('blog',post.section).blocks;return `<article class="post-preview"><a href="${route(post.id)}" class="post-image">${img(post.image,{eager:i===0})}</a><div>${eyebrow(post.date,'PERSONAL JOURNAL')}<h2><a href="${route(post.id)}">${inner(b[0])}</a></h2><div class="prose">${b.slice(1,-1).join('')}</div><a class="text-link" href="${route(post.id)}" aria-label="Read ${esc(text(b[0]))}">Read More... <span aria-hidden="true">↗</span></a></div></article>`}).join('')}</div>`;}
function article(post){const b=sec('blog',post.section).blocks;return `<div class="article-wrap"><a class="back-link" href="${route('blog')}">← All stories</a>${masthead('PERSONAL JOURNAL',inner(sec(post.id,0).blocks[0]),'',post.date)}<figure class="article-image">${img(post.image,{eager:true,large:true})}</figure><article class="article-prose">${html(post.id,1)}</article><div class="article-end">${eyebrow('UM','END OF STORY')}<a href="${route('blog')}">Back to the journal ↗</a></div></div>`;}
const outputs=[['home','Home',home()],['research','Research',research()],['teaching','Teaching',teaching()],['photography','Photography',photography()],['blog','Blog',blog()],...posts.map(p=>[p.id,text(sec(p.id,0).blocks[0]),article(p)])];
for(const [page,title,body]of outputs)writeFileSync(page==='home'?'index.html':page+'.html',layout(page,title,body,{image:posts.find(p=>p.id===page)?.image||'image-002'}));
writeFileSync('404.html',layout('404','Page not found',`<section class="not-found">${eyebrow('404','PAGE NOT FOUND')}<h1>A little<br>off the map.</h1><p>This page may have moved. Explore the portfolio from one of the main destinations.</p><a class="button primary" href="${BASE}">Return home ↗</a><a class="button" href="${route('research')}">Research ↗</a></section>`));
writeFileSync('.nojekyll','');
writeFileSync('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${outputs.map(([p])=>`<url><loc>${p==='home'?SITE:SITE+p+'.html'}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${outputs.length+1} static HTML pages. Base path: ${BASE}. ${assets.length} source image placements; 52 album photographs.`);
